-- Tạo hoặc sử dụng cơ sở dữ liệu QLKS
CREATE DATABASE IF NOT EXISTS QLKS;
USE QLKS;

-- Bảng user
CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50)
);

-- Bảng PhongBan
CREATE TABLE IF NOT EXISTS PhongBan (
    MaPB NVARCHAR(10) PRIMARY KEY NOT NULL,
    TenPB NVARCHAR(50) NOT NULL,
    SDT NVARCHAR(20) NOT NULL,
    Email NVARCHAR(50) NOT NULL
);

-- Bảng NhanVien
CREATE TABLE IF NOT EXISTS NhanVien (
    MaNV NVARCHAR(10) PRIMARY KEY NOT NULL,
    TenNV NVARCHAR(50) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(4) CHECK (GioiTinh IN ('Nam', 'Nu', 'Khac')),
    QuocTich NVARCHAR(50),
    CCCD NVARCHAR(20) NOT NULL,
    DiaChi NVARCHAR(225),
    SDT NVARCHAR(20) NOT NULL,
    ChucVu NVARCHAR(50),
    Luong FLOAT,
    MaPB NVARCHAR(10),
    FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB)
);

-- Bảng KhachHang
CREATE TABLE IF NOT EXISTS KhachHang (
    MaKH INT AUTO_INCREMENT PRIMARY KEY,
    TenKH NVARCHAR(50) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(4) CHECK (GioiTinh IN ('Nam', 'Nu', 'Khac')),
    QuocTich NVARCHAR(50),
    CCCD NVARCHAR(20) NOT NULL,
    SDT NVARCHAR(20) NOT NULL,
    Email NVARCHAR(50),
    IsDeleted BOOLEAN DEFAULT FALSE
);

-- Bảng LoaiPhong
CREATE TABLE IF NOT EXISTS LoaiPhong (
    MaLP NVARCHAR(10) PRIMARY KEY NOT NULL,
    TenLP NVARCHAR(20) NOT NULL,
    Gia FLOAT,
    SoNguoiLonToiDa NUMERIC(10,0),
    SoTreEmToiDa NUMERIC(10,0),
    SoGiuong NUMERIC(10,0)
);

-- Bảng Phong
CREATE TABLE IF NOT EXISTS Phong (
    MaPhong NVARCHAR(10) PRIMARY KEY NOT NULL,
    MaLP NVARCHAR(10),
    TinhTrangPhong NVARCHAR(20),
    NgayDatPhong DATE NULL,
    NgayTraPhong DATE NULL,
    TenKhachHang VARCHAR(100) NULL,
    FOREIGN KEY (MaLP) REFERENCES LoaiPhong(MaLP)
);

-- Bảng ThietBi
CREATE TABLE IF NOT EXISTS ThietBi (
    MaTB NVARCHAR(10) PRIMARY KEY NOT NULL,
    TenTB NVARCHAR(50) NOT NULL,
    Dvt NVARCHAR(20),
    DonGia FLOAT
);

-- Bảng ThietBi_Phong
CREATE TABLE IF NOT EXISTS ThietBi_Phong (
    MaTB NVARCHAR(10),
    MaPhong NVARCHAR(10),
    SoLuong INT,
    PRIMARY KEY (MaTB, MaPhong),
    FOREIGN KEY (MaTB) REFERENCES ThietBi(MaTB),
    FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong)
);

-- Bảng DichVu
CREATE TABLE IF NOT EXISTS DichVu (
    MaDV NVARCHAR(10) PRIMARY KEY NOT NULL,
    TenDV NVARCHAR(50) NOT NULL,
    DonGia FLOAT,
    Dvt NVARCHAR(20)
);

-- Bảng PhieuDangKy
CREATE TABLE IF NOT EXISTS PhieuDangKy (
    MaPDK NVARCHAR(10) PRIMARY KEY NOT NULL,
    NgayLPDK DATE,
    NgayDK DATE,
    NgayHenTra DATE,
    NgayTra DATE,
    HinhThuc NVARCHAR(20),  -- Đã thay đổi kích thước cột từ NVARCHAR(7) thành NVARCHAR(20)
    TienDatCoc FLOAT,
    MaPhong NVARCHAR(10),
    MaNV NVARCHAR(10),
    MaKH INT,
    FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);

-- Bảng HoaDon
CREATE TABLE IF NOT EXISTS HoaDon (
    MaHD NVARCHAR(10) PRIMARY KEY NOT NULL,
    NgayLap DATE,
    TienPhong FLOAT,
    TienDV FLOAT,
    MaNV NVARCHAR(10),
    MaPDK NVARCHAR(10),
    FOREIGN KEY (MaPDK) REFERENCES PhieuDangKy(MaPDK),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

-- Bảng PhieuThu
CREATE TABLE IF NOT EXISTS PhieuThu (
    MaPT NVARCHAR(10) PRIMARY KEY NOT NULL,
    MaHD NVARCHAR(10),
    TongTien FLOAT,
    PhuongThucTT NVARCHAR(20),
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
);

-- Bảng TriAnKH
CREATE TABLE IF NOT EXISTS TriAnKH (
    MaTAKH NVARCHAR(10) PRIMARY KEY NOT NULL,
    MaKH INT,
    TenQua NVARCHAR(20),
    NgayTriAn DATE,
    GiaTri FLOAT,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

-- Bảng PhieuTichDiem
CREATE TABLE IF NOT EXISTS PhieuTichDiem (
    MaPTD NVARCHAR(10) PRIMARY KEY NOT NULL,
    MaKH INT,
    NgayPhieu DATE,
    BienDongDiem FLOAT,
    NguyenNhanBienDongDiem NVARCHAR(225),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

-- Bảng ThuePhong
CREATE TABLE IF NOT EXISTS ThuePhong (
    MaThue INT AUTO_INCREMENT PRIMARY KEY,
    MaPhong NVARCHAR(10) NOT NULL,
    MaKH INT NOT NULL,
    NgayThue DATE NOT NULL,
    NgayKT DATE,
    FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

-- Bảng DoanhThu
CREATE TABLE IF NOT EXISTS DoanhThu (
    MaDT INT AUTO_INCREMENT PRIMARY KEY,
    Ngay DATE NOT NULL,
    TongDoanhThu FLOAT
);
